### ISSUE TITLE
Errors for downloading the dataset COFIE and COFIE-G

### ISSUE THREAD

**Issue by vhientran** [AidaAmini/DyGIE-MECHANIC#1]
Hi @AidaAmini and @tomhoper ,

Thanks for your nice work. Now, I am trying to download two datasets: COFIE and COFIE-G by using the command: bash scripts/data/get_cofie.sh (as you guided). However, I cannot download it, such as:

Connecting to ai2-s2-cofie.s3-us-west-2.amazonaws.com (ai2-s2-cofie.s3-us-west-2.amazonaws.com)|52.218.144.5|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-02-02 16:43:43 ERROR 403: Forbidden.

Could you please help me to download your datasets? Thanks for your help!

**Comment by AidaAmini** [comment]
Hi @angelotran05, 

Thanks for pointing out the problem. I have fixed the download link.

Best

**Comment by vhientran** [comment]
Thanks for considering the problem. However, I have just tried to download your dataset, and still get the same error:

bash scripts/data/get_cofie.sh
mkdir: cannot create directory ‘data/’: File exists
--2021-02-03 15:31:52--  https://ai2-s2-cofie.s3-us-west-2.amazonaws.com/data.tar.gz
Resolving ai2-s2-cofie.s3-us-west-2.amazonaws.com (ai2-s2-cofie.s3-us-west-2.amazonaws.com)... 52.218.132.217
Connecting to ai2-s2-cofie.s3-us-west-2.amazonaws.com (ai2-s2-cofie.s3-us-west-2.amazonaws.com)|52.218.132.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-02-03 15:31:52 ERROR 403: Forbidden.

**Comment by AidaAmini** [comment]
So, I have made a change in the scripts/data/get_cofie.sh file now the path is pointing to data.zip which is the correct extension. You can see the changes in the newest commit.

**Comment by vhientran** [comment]
Now, I already got your dataset. Thanks for your help!
